# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  batch : "true"
  branches:
    include:
      - master
  paths:
    include:
      - ./*

pool:
  vmImage: ubuntu-latest
  
stages:
  - stage: TestStage
    variables:
    - group: "Test Var Group"
    jobs:
      - job: Test
        steps:
          - script: echo $(user)
  - stage: AcceptanceStage
    variables:
      - group:  "Acceptance Var Group"
    jobs:
      - job: Acceptance
        steps:
          - script: echo $(user)
  - stage: Production Stage
    variables:
      - group:  "Production Var Group"
    jobs:
      - job: Production
        steps:
          - script: echo $(user)

